#include "keyboard/key_map.h"

#include <windows.h>

std::unordered_map<int, std::string> keyMap = {
	{VK_LBUTTON, "LBUTTON"},
	{VK_RBUTTON, "RBUTTON"},
	{VK_CANCEL, "CANCEL"},
	{VK_MBUTTON, "MBUTTON"},
    {VK_MENU, "ALT"},
    {VK_CONTROL, "CTRL"},
    {VK_SHIFT, "SHIFT"},
    {VK_RETURN, "ENTER"},
    {VK_ESCAPE, "ESC"},
    {VK_SPACE, "SPACE"},
    {VK_TAB, "TAB"},
    {VK_LEFT, "LEFT"},
    {VK_UP, "UP"},
    {VK_RIGHT, "RIGHT"},
    {VK_DOWN, "DOWN"},
    {VK_DELETE, "DELETE"},
    {VK_BACK, "BACKSPACE"},
    {VK_CAPITAL, "CAPSLOCK"},
    {VK_LWIN, "LWIN"},
    {VK_RWIN, "RWIN"},
    {VK_APPS, "APPS"},
    {VK_OEM_1, "OEM_1"},   //  ; :
    {VK_OEM_PLUS, "OEM_PLUS"}, //  = +
    {VK_OEM_COMMA, "OEM_COMMA"}, //  , <
    {VK_OEM_MINUS, "OEM_MINUS"}, //  - _
    {VK_OEM_PERIOD, "OEM_PERIOD"}, //  . >
    {VK_OEM_2, "OEM_2"},   //  / ?
    {VK_OEM_3, "OEM_3"},   //  ` ~
    {VK_OEM_4, "OEM_4"},   //  [ {
    {VK_OEM_5, "OEM_5"},   //  \ |
    {VK_OEM_6, "OEM_6"},   //  ] }
    {VK_OEM_7, "OEM_7"},   //  ' "
    {VK_F1, "F1"},
    {VK_F2, "F2"},
    {VK_F3, "F3"},
    {VK_F4, "F4"},
    {VK_F5, "F5"},
    {VK_F6, "F6"},
    {VK_F7, "F7"},
    {VK_F8, "F8"},
    {VK_F9, "F9"},
    {VK_F10, "F10"},
    {VK_F11, "F11"},
    {VK_F12, "F12"},
    {VK_NUMLOCK, "NUMLOCK"},
    {VK_SCROLL, "SCROLLLOCK"},
    {VK_VOLUME_MUTE, "MUTE"},
    {VK_VOLUME_DOWN, "VOLUMEDOWN"},
    {VK_VOLUME_UP, "VOLUMEUP"},
    {VK_MEDIA_NEXT_TRACK, "NEXT"},
    {VK_MEDIA_PREV_TRACK, "PREV"},
    {VK_MEDIA_PLAY_PAUSE, "PLAY"},
    {VK_MEDIA_STOP, "STOP"},
	{'0', "0"},
	{'1', "1"},
	{'2', "2"},
	{'3', "3"},
	{'4', "4"},
	{'5', "5"},
	{'6', "6"},
	{'7', "7"},
	{'8', "8"},
	{'9', "9"},
	{':', ":"},
	{';', ";"},
	{'<', "<"},
	{'=', "="},
	{'>', ">"},
	{'?', "?"},
	{'A', "A"},
	{'B', "B"},
	{'C', "C"},
	{'D', "D"},
	{'E', "E"},
	{'F', "F"},
	{'G', "G"},
	{'H', "H"},
	{'I', "I"},
	{'J', "J"},
	{'K', "K"},
	{'L', "L"},
	{'M', "M"},
	{'N', "N"},
	{'O', "O"},
	{'P', "P"},
	{'Q', "Q"},
	{'R', "R"},
	{'S', "S"},
	{'T', "T"},
	{'U', "U"},
	{'V', "V"},
	{'W', "W"},
	{'X', "X"},
	{'Y', "Y"},
	{'Z', "Z"},
};